<Project>

  <PropertyGroup>
	  <Version>2.0.7</Version>
	  <AssemblyVersion>2.0.7</AssemblyVersion>
    <Authors>Tatsuro Shibamura;Ingo Herbote</Authors>
    <Company>Ingo Herbote</Company>
    <Copyright>&#169; Tatsuro Shibamura and Ingo Herbote</Copyright>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/w8tcha/OEmbed.Core</PackageProjectUrl>
    <PackageIcon>oembed.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/w8tcha/OEmbed.Core.git</RepositoryUrl>
    <DebugType>embedded</DebugType>
    <LangVersion>latest</LangVersion>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
  </PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net481' ">
		<SignAssembly>True</SignAssembly>
		<DelaySign>False</DelaySign>
		<AssemblyOriginatorKeyFile>../OEmbed.Core.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

</Project>
